const phrasePairs: Array<[string, string]> = [
  ['Production Control Overview', '生产控制总览'],
  ['New Project Setup', '新建项目设置'],
  ['Asset Library Board', '资产库看板'],
  ['Creative Graph Workbench', '创作图谱工作台'],
  ['Shot Prompt Console', '镜头提示词控制台'],
  ['Package Export Review', '交接包导出评审'],
  ['Result Review Desk', '结果评审台'],
  ['Project Health View', '项目健康视图'],
  ['Creative Graph Canvas', '创作图谱画布'],
  ['Shot Package Builder', '镜头交接包构建器'],
  ['Instruction Preview', '指令预览'],
  ['Runtime Queue', '运行队列'],
  ['Workbench Frame', '工作台框架'],
  ['Security Health', '安全健康状态'],
  ['Acceptance Dashboard', '验收看板'],
  ['Scope Console', '边界控制台'],
  ['Production Flow', '生产流程'],
  ['Design Module', '设计模块'],
  ['Design Modules', '设计模块'],
  ['Production Flow Map', '生产流程地图'],
  ['Product Scope', '产品边界'],
  ['Project Setup', '项目创建'],
  ['Asset Library', '资产库'],
  ['Creative Graph', '创作图谱'],
  ['Shot & Prompt', '镜头与提示词'],
  ['Package Export', '交接包导出'],
  ['Result Review', '结果评审'],
  ['Local Storage', '本地存储'],
  ['Asset Continuity', '资产连续性'],
  ['Script to Package', '剧本到交接包'],
  ['Instruction Stack', '指令栈'],
  ['Runtime Adapters', '运行适配器'],
  ['Workbench UX', '工作台体验'],
  ['Security & Observability', '安全与可观测性'],
  ['Delivery & Acceptance', '交付与验收'],
  ['Product Boundary', '产品边界'],
  ['User Workflows', '用户工作流'],
  ['Glossary', '术语表'],
  ['Directory Layout', '目录布局'],
  ['Schema and Migration', '结构与迁移'],
  ['Save Lock Recovery', '保存锁恢复'],
  ['Health Check', '健康检查'],
  ['Nodes and Edges', '节点与边'],
  ['Graph State Machine', '图谱状态机'],
  ['Context Resolution', '上下文解析'],
  ['Consistency Rules', '一致性规则'],
  ['Asset Ingestion and Indexing', '资产导入与索引'],
  ['Asset Binding and Lineage', '资产绑定与血缘'],
  ['Continuity Rules', '连续性规则'],
  ['Deletion and Recovery', '删除与恢复'],
  ['Script to Scene', '剧本拆场'],
  ['Shot Card Lifecycle', '镜头卡生命周期'],
  ['Result Ingestion and Review', '结果导入与评审'],
  ['Instruction Compile Order', '指令编译顺序'],
  ['Skill Registry and Routing', '能力包注册与路由'],
  ['Output Contracts', '输出契约'],
  ['Conflict Handling', '冲突处理'],
  ['Runtime Gateway', '运行网关'],
  ['Image Generation Adapter', '图像生成适配器'],
  ['Provider Handoff Adapter', '供应商交接适配器'],
  ['Runtime Errors and Retry', '运行错误与重试'],
  ['Workspace Layout', '工作区布局'],
  ['Canvas Interactions', '画布交互'],
  ['Inspector and Task Panels', '检查器与任务面板'],
  ['Production Feedback', '生产反馈'],
  ['Path Guard and Permissions', '路径守卫与权限'],
  ['Privacy and Redaction', '隐私与脱敏'],
  ['Audit Events', '审计事件'],
  ['Observability and Recovery', '可观测性与恢复'],
  ['Delivery Slices', '交付切片'],
  ['Acceptance Matrix', '验收矩阵'],
  ['Test Strategy', '测试策略'],
  ['Release Readiness', '发布就绪'],
  ['Future App Surface', '未来应用工作面'],
  ['Semi-real App Sketch', '半真实应用草图'],
  ['Inspector / Rules', '检查器 / 规则'],
  ['Task & Health Rail', '任务与健康侧栏'],
  ['Queue / Health', '队列 / 健康'],
  ['Boundary Review', '边界评审'],
  ['Local Project', '本地项目'],
  ['Graph Domain', '图谱领域'],
  ['Script Production', '剧本生产'],
  ['Compile Stack', '编译栈'],
  ['UX Surface', '体验界面'],
  ['Privacy & Audit', '隐私与审计'],
  ['Delivery Gates', '交付门禁'],
  ['End-to-end loop', '端到端闭环'],
  ['Local-first root', '本地优先根目录'],
  ['Continuity shelf', '连续性资产栏'],
  ['Main canvas', '主画布'],
  ['Pre-run preview', '运行前预览'],
  ['Handoff state', '交接状态'],
  ['Take review', '成片评审'],
  ['Current Shot', '当前镜头'],
  ['Linked Assets', '关联资产'],
  ['Next Gate', '下一门禁'],
  ['Project name', '项目名称'],
  ['Root path', '根路径'],
  ['Directory plan', '目录规划'],
  ['Provider profile', '供应商配置'],
  ['Privacy default', '隐私默认值'],
  ['Character / face_ref_01', '角色 / 面部参考 01'],
  ['Scene / rain_alley', '场景 / 雨巷'],
  ['Style / dusk palette', '风格 / 黄昏调色板'],
  ['Prop / old_phone', '道具 / 旧手机'],
  ['Bindings', '绑定关系'],
  ['Lineage', '血缘'],
  ['Impact', '影响'],
  ['Selected node', '选中节点'],
  ['Valid relations', '合法关系'],
  ['Impact report', '影响报告'],
  ['Shot 012 card', '镜头 012 卡片'],
  ['Context bundle', '上下文包'],
  ['Output contract', '输出契约'],
  ['Conflict check', '冲突检查'],
  ['Compile order', '编译顺序'],
  ['External data range', '外部数据范围'],
  ['Run state', '运行状态'],
  ['Reference files', '参考文件'],
  ['External destination', '外部目标'],
  ['Shot gates', '镜头门禁'],
  ['Profile', '配置'],
  ['Portability', '可移植性'],
  ['Revision note', '修订备注'],
  ['Review action', '评审动作'],
  ['Audit', '审计'],
  ['Project production loop', '项目生产闭环'],
  ['External provider submit', '外部供应商提交'],
  ['Cloud collaboration', '云端协作'],
  ['Decision rule', '决策规则'],
  ['Evidence', '证据'],
  ['Provider mention', '供应商提及'],
  ['Path mode', '路径模式'],
  ['Autosave', '自动保存'],
  ['External ref', '外部引用'],
  ['Character: 小夏', '角色：小夏'],
  ['Character ref A', '角色参考 A'],
  ['Scene loft', '阁楼场景'],
  ['Prop phone', '手机道具'],
  ['Required fields', '必填字段'],
  ['References', '引用'],
  ['State gate', '状态门禁'],
  ['Project principles', '项目原则'],
  ['Shot context', '镜头上下文'],
  ['Output schema', '输出结构'],
  ['Skill', '能力包'],
  ['Data wrapping', '数据包装'],
  ['Conflict', '冲突'],
  ['PromptRun 84', '提示词运行 84'],
  ['Image output', '图像输出'],
  ['Handoff profile', '交接配置'],
  ['Retry policy', '重试策略'],
  ['Error mapping', '错误映射'],
  ['Canvas cluster', '画布集群'],
  ['Asset shelf', '资产栏'],
  ['Health strip', '健康条'],
  ['Task Queue', '任务队列'],
  ['Path guard', '路径守卫'],
  ['External task', '外部任务'],
  ['Credential scan', '凭据扫描'],
  ['Audit event', '审计事件'],
  ['Redaction', '脱敏'],
  ['Support bundle', '支持包'],
  ['Local project slice', '本地项目切片'],
  ['Package export slice', '交接包导出切片'],
  ['Redaction gate', '脱敏门禁'],
  ['Matrix', '矩阵'],
  ['Release gate', '发布门禁'],
  ['Docs sync', '文档同步'],
  ['GraphNode', '图谱节点'],
  ['Domain Object', '领域对象'],
  ['Run Record', '运行记录'],
  ['Health Gate', '健康门禁'],
  ['Imported Asset', '已导入资产'],
  ['Locked Binding', '锁定绑定'],
  ['Shot Context', '镜头上下文'],
  ['Project Rules', '项目规则'],
  ['Context Bundle', '上下文包'],
  ['Skill / Template', '能力包 / 模板'],
  ['Top Bar', '顶部栏'],
  ['Left Panel', '左侧面板'],
  ['Canvas', '画布'],
  ['Inspector + Bottom', '检查器 + 底栏'],
  ['Path Guard', '路径守卫'],
  ['Audit Event', '审计事件'],
  ['Recovery Report', '恢复报告'],
  ['User Action', '用户动作'],
  ['Guard', '守卫'],
  ['Observability', '可观测性'],
  ['Functional', '功能'],
  ['Data', '数据'],
  ['Errors', '错误'],
  ['Recovery', '恢复'],
  ['Source Documents', '来源文档'],
  ['Module README', '模块说明'],
  ['Key Rules', '关键规则'],
  ['Key Invariants', '关键不变量'],
  ['Error Semantics', '错误语义'],
  ['Recovery Semantics', '恢复语义'],
  ['Related Design Modules', '关联设计模块'],
  ['Related Production Flow', '关联生产流程'],
  ['Production State Distribution', '生产状态分布'],
  ['Markdown Coverage by Module', '各模块标记文档覆盖'],
]

const tokenPairs: Array<[string, string]> = [
  ['source: docs/design', '来源：设计文档'],
  ['prototype: review-only', '原型：仅评审'],
  ['runtime: no backend', '运行时：无后端'],
  ['architecture/redacted-production-architecture.md', '架构脱敏生产方案'],
  ['details/README.md', '设计索引'],
  ['project.json、graph.json、assets index、prompts/runs、packages、audit', '项目清单、资产索引、提示词与运行记录、交接包、审计'],
  ['project.json、graph.json、principles.md、style_bible.md', '单一项目清单、原则和风格设定'],
  ['packages/{package_id}/manifest.json、prompts、assets、checksums 和 audit', '交接包目录、清单、提示词、资产、校验和与审计'],
  ['GraphDocument 的 nodes、edges、viewport、layout 和 version', '图谱文档的节点、边、视口、布局和版本'],
  ['Shot、PromptRun、GenerationPackage、VideoResult 和 Review Status', '镜头、提示词运行、生成交接包、视频结果和评审状态'],
  ['RuntimeGateway、ProviderProfile、HandoffAdapter、ImageGenerationAdapter', '运行网关、供应商配置、交接适配器、图像生成适配器'],
  ['Project、Creative Graph、Shot、PromptRun、GenerationPackage、Take 和 Review Status', '项目、创作图谱、镜头、提示词运行、生成交接包、成片和评审状态'],
  ['Asset、AssetBinding、AssetSource、缩略图、digest 和 lineage', '资产、资产绑定、资产来源、缩略图、摘要和血缘'],
  ['ShotCard', '镜头卡'],
  ['ContextBundle', '上下文包'],
  ['ProductionFrame', '生产组'],
  ['ReferenceGroup', '参考组'],
  ['FrameRun', '生产组运行'],
  ['PromptRun', '提示词运行'],
  ['GenerationPackage', '生成交接包'],
  ['VideoResult', '视频结果'],
  ['ImpactReport', '影响报告'],
  ['GraphDocument', '图谱文档'],
  ['GraphNode.refId', '图谱节点引用标识'],
  ['GraphNode', '图谱节点'],
  ['AssetBinding', '资产绑定'],
  ['AssetSource', '资产来源'],
  ['RuntimeGateway', '运行网关'],
  ['ProviderProfile', '供应商配置'],
  ['HandoffAdapter', '交接适配器'],
  ['ImageGenerationAdapter', '图像生成适配器'],
  ['Provider capability', '供应商能力'],
  ['provider capability', '供应商能力'],
  ['capability missing', '能力缺失'],
  ['capability', '能力'],
  ['Shot.status', '镜头状态'],
  ['GenerationPackage.status', '生成交接包状态'],
  ['reviewStatus', '评审状态'],
  ['filePath', '文件路径'],
  ['packageId', '交接包标识'],
  ['shotId', '镜头标识'],
  ['sourceAssetId', '源资产标识'],
  ['promptRunId', '提示词运行标识'],
  ['package_reference_missing', '交接包引用缺失'],
  ['path_traversal_rejected', '路径穿越已拒绝'],
  ['symlink_escape_rejected', '符号链接逃逸已拒绝'],
  ['external_write_unconfirmed', '外部写入未确认'],
  ['credential_detected', '检测到凭据'],
  ['silent_upload_blocked', '静默上传已阻断'],
  ['redaction_failed', '脱敏失败'],
  ['audit_write_failed', '审计写入失败'],
  ['audit_event_invalid', '审计事件无效'],
  ['health_check_failed', '健康检查失败'],
  ['recovery_not_applicable', '恢复不适用'],
  ['debug_record_unavailable', '调试记录不可用'],
  ['dependency_unmet', '依赖未满足'],
  ['acceptance_gap', '验收缺口'],
  ['docs_out_of_sync', '文档未同步'],
  ['matrix_row_missing', '矩阵行缺失'],
  ['dimension_missing', '维度缺失'],
  ['evidence_missing', '证据缺失'],
  ['test_fixture_missing', '测试样例缺失'],
  ['manual_step_blocked', '手动步骤被阻断'],
  ['docs_validation_failed', '文档校验失败'],
  ['release_gate_failed', '发布门禁失败'],
  ['redaction_gate_failed', '脱敏门禁失败'],
  ['provider_coupling_detected', '检测到供应商耦合'],
  ['timeout、cancelled、provider_error、output_invalid', '超时、已取消、供应商错误、输出无效'],
  ['unsupported node kind', '不支持的节点类型'],
  ['invalid relation', '无效关系'],
  ['cycle detected', '检测到循环'],
  ['stale graph version', '图谱版本过期'],
  ['missing required ref', '缺少必需引用'],
  ['broken reference placeholder', '断链引用占位'],
  ['belongs_to / uses / produces', '归属 / 使用 / 产出'],
  ['context too large', '上下文过大'],
  ['run_output_invalid', '运行输出无效'],
  ['provider error', '供应商错误'],
  ['handoff profile invalid', '交接配置无效'],
  ['result binding ambiguous', '结果绑定不明确'],
  ['wrong package linkage', '交接包链接错误'],
  ['required field missing', '必填字段缺失'],
  ['dirty context', '上下文有变更'],
  ['ambiguous scene split', '拆场不明确'],
  ['invalid script input', '剧本输入无效'],
  ['write validation failed', '写入校验失败'],
  ['dirty shutdown', '异常关闭'],
  ['stale lock', '过期锁'],
  ['active lock takeover', '活动锁接管'],
  ['health check incomplete', '健康检查未完成'],
  ['unsafe export', '导出不安全'],
  ['digest mismatch', '摘要不一致'],
  ['unsupported schema', '不支持的结构版本'],
  ['failed migration', '迁移失败'],
  ['unsupported media type', '不支持的媒体类型'],
  ['locked binding', '锁定绑定'],
  ['orphan output asset', '孤立输出资产'],
  ['continuity conflict', '连续性冲突'],
  ['missing locked asset', '缺少锁定资产'],
  ['referenced asset delete blocked', '被引用资产删除已阻断'],
  ['missing file warning', '缺失文件警告'],
  ['export blocking', '导出阻断'],
  ['skill unavailable', '能力包不可用'],
  ['version mismatch', '版本不匹配'],
  ['run_output_invalid', '运行输出无效'],
  ['schema missing', '结构缺失'],
  ['instruction conflict', '指令冲突'],
  ['material as instruction', '素材被当成指令'],
  ['queue unavailable', '队列不可用'],
  ['cancel failed', '取消失败'],
  ['provider rate limit', '供应商限流'],
  ['output missing', '输出缺失'],
  ['external write unconfirmed', '外部写入未确认'],
  ['layout state unavailable', '布局状态不可用'],
  ['panel overflow', '面板溢出'],
  ['task panel stale', '任务面板已过期'],
  ['autosave failed', '自动保存失败'],
  ['export blocked', '导出被阻断'],
  ['studio root', '工作室根目录'],
  ['Studio root', '工作室根目录'],
  ['project root', '项目根目录'],
  ['project.create/open', '项目创建/打开'],
  ['lock takeover', '锁接管'],
  ['health audit', '健康审计'],
  ['active lock', '活动锁'],
  ['backups', '备份'],
  ['managed reference', '托管引用'],
  ['context digest', '上下文摘要'],
  ['compile request', '编译请求'],
  ['provider/profile/adapter', '供应商/配置/适配器'],
  ['provider profile', '供应商配置'],
  ['provider/profile', '供应商/配置'],
  ['profile/adapter', '配置/适配器'],
  ['style bible', '风格设定'],
  ['style_bible.md', '风格设定文档'],
  ['principles.md', '原则文档'],
  ['manifest.json', '清单文件'],
  ['manifest', '清单'],
  ['checksums', '校验和'],
  ['prompts', '提示词'],
  ['prompt', '提示词'],
  ['packages', '交接包'],
  ['package', '交接包'],
  ['assets index', '资产索引'],
  ['assets', '资产'],
  ['asset', '资产'],
  ['audit', '审计'],
  ['digest', '摘要'],
  ['lineage', '血缘'],
  ['schema', '结构'],
  ['profile', '配置'],
  ['provider', '供应商'],
  ['adapter', '适配器'],
  ['graph', '图谱'],
  ['project', '项目'],
  ['compile', '编译'],
  ['review', '评审'],
  ['take', '成片'],
  ['approved', '已通过'],
  ['rejected', '已拒绝'],
  ['created', '已创建'],
  ['serves shot-level loop', '服务镜头级闭环'],
  ['local audit required', '需要本地审计'],
  ['adapter/profile only', '仅适配器/配置'],
  ['shot_012', '镜头_012'],
  ['refs', '引用'],
  ['autosave', '自动保存'],
  ['package check', '交接包检查'],
  ['result review', '结果评审'],
  ['health bootstrap', '健康初始化'],
  ['migration', '迁移'],
  ['default-handoff', '默认交接'],
  ['layout autosave', '布局自动保存'],
  ['context resolver', '上下文解析器'],
  ['confirmation required', '需要确认'],
  ['after asset change', '资产变化后'],
  ['after manifest ok', '清单通过后'],
  ['audit event', '审计事件'],
  ['Bound Shot', '已绑定镜头'],
  ['schema ok', '结构正常'],
  ['schema 1.0.0', '结构版本 1.0.0'],
  ['schema missing', '结构缺失'],
  ['schema validation', '结构校验'],
  ['supported write', '支持写入'],
  ['imported', '已导入'],
  ['confirmed', '已确认'],
  ['locked ref', '引用已锁定'],
  ['locked continuity', '连续性已锁定'],
  ['locked lighting', '灯光已锁定'],
  ['locked', '已锁定'],
  ['context_ready', '上下文就绪'],
  ['prompt_ready', '提示词就绪'],
  ['package_ready', '交接包就绪'],
  ['pending_review', '待评审'],
  ['needs_revision', '需要修订'],
  ['result_received', '结果已回收'],
  ['handed_off', '已交接'],
  ['waiting_user', '等待用户'],
  ['ready', '就绪'],
  ['stale', '已过期'],
  ['dirty', '有变更'],
  ['invalid', '无效'],
  ['generated', '已生成'],
  ['draft', '草稿'],
  ['running', '运行中'],
  ['completed', '已完成'],
  ['complete', '已完成'],
  ['clean', '干净'],
  ['clean shutdown', '干净关闭'],
  ['available', '可用'],
  ['required', '必需'],
  ['not required', '无需执行'],
  ['not needed', '无需执行'],
  ['waiting', '等待中'],
  ['verified', '已验证'],
  ['manual proof', '手动证明'],
  ['pending evidence', '待补证据'],
  ['ready to run', '可运行'],
  ['requires confirmation', '需要确认'],
  ['confirmation required', '需要确认'],
  ['needs confirmation', '需要确认'],
  ['needs rule choice', '需要选择规则'],
  ['manual submit', '手动提交'],
  ['manual video handoff', '手动视频交接'],
  ['manual gate', '手动门禁'],
  ['handoff only', '仅交接'],
  ['out of scope', '范围外'],
  ['in scope', '范围内'],
  ['local only', '仅本地'],
  ['local-first', '本地优先'],
  ['local audit required', '需要本地审计'],
  ['adapter/profile only', '仅适配器/配置'],
  ['project-relative', '项目相对路径'],
  ['relative paths only', '仅相对路径'],
  ['relative paths', '相对路径'],
  ['no active owner', '无活动占用者'],
  ['no backend', '无后端'],
  ['source data', '来源数据'],
  ['source and grouping', '来源与分组'],
  ['source', '来源'],
  ['grouping', '分组'],
  ['context inputs', '上下文输入'],
  ['compiled production unit', '编译后的生产单元'],
  ['handoff and review evidence', '交接与评审证据'],
  ['digest ok', '摘要正常'],
  ['digest 91a4', '摘要 91a4'],
  ['digest + source', '摘要 + 来源'],
  ['digest + metadata', '摘要 + 元数据'],
  ['source + relative path', '来源 + 相对路径'],
  ['2 warnings', '2 个警告'],
  ['1 warning', '1 个警告'],
  ['1 blocking', '1 个阻断项'],
  ['3', '3'],
  ['18 nodes / 22 edges', '18 个节点 / 22 条边'],
  ['2 ready / 1 stale', '2 个就绪 / 1 个过期'],
  ['external task needs confirm', '外部任务需要确认'],
  ['shot_012 context_ready', '镜头_012 上下文就绪'],
  ['4 refs / 2 locked', '4 个引用 / 2 个锁定'],
  ['prompt preview', '提示词预览'],
  ['1 stale', '1 个过期'],
  ['waiting take', '等待成片'],
  ['used by 4 shots', '被 4 个镜头使用'],
  ['continuity rule', '连续性规则'],
  ['missing file', '缺失文件'],
  ['missing source', '缺失来源'],
  ['imported -> package v03', '已导入 -> 交接包 v03'],
  ['2 stale packages', '2 个过期交接包'],
  ['thumbnail job', '缩略图任务'],
  ['relink action', '重新链接动作'],
  ['version 28', '版本 28'],
  ['stale after asset change', '资产变化后过期'],
  ['2 packages affected', '2 个交接包受影响'],
  ['dirty after asset change', '资产变化后有变更'],
  ['duration 4s / camera dolly', '时长 4 秒 / 推轨镜头'],
  ['scene + 2 characters + 4 refs', '场景 + 2 个角色 + 4 个引用'],
  ['shot_prompt.v2', '镜头提示词 v2'],
  ['principles > context > skill > schema', '原则 > 上下文 > 能力包 > 结构'],
  ['preview before submit', '提交前预览'],
  ['not created until confirm', '确认后才创建'],
  ['draft -> ready', '草稿 -> 就绪'],
  ['8 / 8 present', '8 / 8 已存在'],
  ['package_ready after manifest ok', '清单通过后交接包就绪'],
  ['copy-check enabled', '复制检查已启用'],
  ['manifest validation', '清单校验'],
  ['package.export.requested', '交接包.导出.已请求'],
  ['needs continuity fix', '需要修复连续性'],
  ['approve / reject / needs_revision', '通过 / 拒绝 / 需要修订'],
  ['package -> result -> take', '交接包 -> 结果 -> 成片'],
  ['review.status.changed', '评审.状态.已变更'],
  ['result import', '结果导入'],
  ['revision task', '修订任务'],
  ['camera/action/duration ok', '镜头/动作/时长正常'],
  ['4 assets included', '包含 4 个资产'],
  ['await handoff mark', '等待交接标记'],
  ['priority 1', '优先级 1'],
  ['script as data', '剧本文本作为数据'],
  ['none', '无'],
  ['running 62%', '运行中 62%'],
  ['await validation', '等待校验'],
  ['default-video', '默认视频'],
  ['new run only', '仅创建新运行'],
  ['rate_limit_retryable', '限流可重试'],
  ['queue depth', '队列深度'],
  ['cancel token', '取消令牌'],
  ['nodes + edges + badges', '节点 + 边 + 徽标'],
  ['drag to bind', '拖拽绑定'],
  ['Shot 012 fields', '镜头 012 字段'],
  ['run / export / import', '运行 / 导出 / 导入'],
  ['open object history', '打开对象历史'],
  ['blocked by missing asset', '因资产缺失被阻断'],
  ['blocked sample', '样例被阻断'],
  ['report safe', '报告安全'],
  ['assets excluded', '已排除资产'],
  ['6 domains', '6 个领域'],
  ['6 dimensions', '6 个维度'],
  ['portability proof required', '需要可移植证明'],
  ['part of done', '完成定义的一部分'],
  ['9 steps', '9 步'],
  ['failure path', '失败路径'],
  ['highest priority', '最高优先级'],
  ['Shot data as data', '镜头数据作为数据'],
  ['versioned routing', '带版本路由'],
  ['schema gate', '结构门禁'],
  ['new attempt', '新尝试'],
  ['events + progress', '事件 + 进度'],
  ['user can retry', '用户可重试'],
  ['validated output', '已校验输出'],
  ['retry or cancel', '重试或取消'],
  ['manual choice', '手动选择'],
  ['attempt record', '尝试记录'],
  ['retryable flag', '可重试标记'],
  ['request summary', '请求摘要'],
  ['input digest', '输入摘要'],
  ['output / error', '输出 / 错误'],
  ['immutable history', '不可变历史'],
  ['project / save / queue', '项目 / 保存 / 队列'],
  ['assets / scripts / search', '资产 / 剧本 / 搜索'],
  ['Creative Graph', '创作图谱'],
  ['validation / tasks / health', '校验 / 任务 / 健康'],
  ['project context', '项目上下文'],
  ['top bar', '顶部栏'],
  ['asset/script source', '资产/剧本来源'],
  ['left panel', '左侧面板'],
  ['graph canvas', '图谱画布'],
  ['nodes and edges', '节点与边'],
  ['inspector tabs', '检查器标签'],
  ['edit and validate', '编辑与校验'],
  ['running tasks', '运行任务'],
  ['bottom bar', '底栏'],
  ['health and errors', '健康与错误'],
  ['reject unsafe path', '拒绝不安全路径'],
  ['no local secret leak', '不泄漏本地密钥'],
  ['who / what / when', '谁 / 什么 / 何时'],
  ['diagnostic without secrets', '无敏感信息诊断'],
  ['import/export', '导入/导出'],
  ['explicit action', '显式动作'],
  ['confirm external write', '确认外部写入'],
  ['path check', '路径检查'],
  ['allow or reject', '允许或拒绝'],
  ['redact', '脱敏'],
  ['safe report', '安全报告'],
  ['audit', '审计'],
  ['event jsonl', '事件 jsonl'],
  ['support bundle', '支持包'],
  ['redacted', '已脱敏'],
  ['7 production pages', '7 个生产页面'],
  ['project / graph / package / result', '项目 / 图谱 / 交接包 / 结果'],
  ['blocking + warning', '阻断 + 警告'],
  ['retry / relink / re-export', '重试 / 重新链接 / 重新导出'],
]

const wordPairs: Array<[string, string]> = [
  ['Production', '生产'],
  ['Design', '设计'],
  ['Module', '模块'],
  ['Overview', '总览'],
  ['Project', '项目'],
  ['Graph', '图谱'],
  ['Asset', '资产'],
  ['Assets', '资产'],
  ['Script', '剧本'],
  ['Scene', '场次'],
  ['Shot', '镜头'],
  ['Prompt', '提示词'],
  ['Package', '交接包'],
  ['Result', '结果'],
  ['Review', '评审'],
  ['Take', '成片'],
  ['Character', '角色'],
  ['Prop', '道具'],
  ['Style', '风格'],
  ['Runtime', '运行时'],
  ['Run', '运行'],
  ['Runs', '运行'],
  ['Provider', '供应商'],
  ['Adapter', '适配器'],
  ['Profile', '配置'],
  ['Handoff', '交接'],
  ['Queue', '队列'],
  ['Health', '健康'],
  ['Inspector', '检查器'],
  ['Canvas', '画布'],
  ['Lineage', '血缘'],
  ['Audit', '审计'],
  ['Gate', '门禁'],
  ['State', '状态'],
  ['Status', '状态'],
  ['Context', '上下文'],
  ['Binding', '绑定'],
  ['Bindings', '绑定'],
  ['Reference', '引用'],
  ['References', '引用'],
  ['External', '外部'],
  ['Local', '本地'],
  ['Security', '安全'],
  ['Privacy', '隐私'],
  ['Acceptance', '验收'],
  ['Release', '发布'],
  ['Recovery', '恢复'],
  ['Error', '错误'],
  ['Errors', '错误'],
  ['Warning', '警告'],
  ['Blocked', '已阻断'],
  ['Draft', '草稿'],
  ['Ready', '就绪'],
  ['Flow', '流程'],
  ['Map', '地图'],
  ['Console', '控制台'],
  ['Dashboard', '看板'],
  ['Surface', '界面'],
  ['Frame', '框架'],
  ['Root', '根目录'],
  ['Node', '节点'],
  ['Nodes', '节点'],
  ['Edge', '边'],
  ['Edges', '边'],
  ['Schema', '结构'],
  ['Lock', '锁'],
  ['App', '应用'],
  ['AI', '人工智能'],
  ['ID', '标识'],
  ['README', '说明'],
]

const cleanupPairs: Array<[string, string]> = [
  ['交接包_就绪 after 清单正常', '清单通过后交接包就绪'],
  ['交接包_就绪 after 清单 正常', '清单通过后交接包就绪'],
  ['p评审 before 提交', '提交前预览'],
  ['运行 records', '运行记录'],
  ['提交ted', '已提交'],
  ['run 提交', '提交运行'],
  ['运行 record', '运行记录'],
  ['ok', '正常'],
  ['就绪 to 运行', '可运行'],
  ['确认 handoff', '确认交接'],
  ['confirm 运行', '确认运行'],
  ['资产 index', '资产索引'],
  ['项目-relative', '项目相对路径'],
  ['新 run', '新运行'],
  [' run', ' 运行'],
  ['impact 报告 failed', '影响报告失败'],
  ['Studio 根目录', '工作室根目录'],
  ['ref 变化', '引用变化'],
  ['缺失 ref', '缺失引用'],
  ['稳定 id', '稳定标识'],
  ['Context Digest', '上下文摘要'],
  ['上下文 Digest', '上下文摘要'],
  ['relative 路径', '相对路径'],
  ['编译d production unit', '编译后的生产单元'],
  ['handoff and 评审 evidence', '交接与评审证据'],
  ['handoff evidence', '交接证据'],
  ['failed / 等待用户', '失败 / 等待用户'],
  ['User', '用户'],
  ['Workbench', '工作台'],
  ['项目 Files', '项目文件'],
  ['元数据数据', '元数据'],
  ['meta数据', '元数据'],
  ['validate', '校验'],
  ['临时文件 write', '写临时文件'],
  ['atomic 重命名', '原子重命名'],
  ['recover / rollback', '恢复 / 回滚'],
  ['审计 trail', '审计轨迹'],
  ['context_有变更', '上下文有变更'],
  ['已过期 until re-导出', '重新导出前过期'],
  ['Template', '模板'],
  ['Output Contract', '输出契约'],
  ['结构 gate', '结构门禁'],
  ['attempt_已创建', '尝试已创建'],
  ['failed_retryable', '失败可重试'],
  ['attempt', '尝试'],
  ['confirm run', '确认运行'],
  ['submit', '提交'],
  ['error mapping', '错误映射'],
  ['input 摘要', '输入摘要'],
  ['Bottom Bar', '底栏'],
  ['save / queue', '保存 / 队列'],
  ['scripts / search', '剧本 / 搜索'],
  ['图谱 View', '图谱视图'],
  ['Navigation', '导航'],
  ['项目 context', '项目上下文'],
  ['资产/script 来源', '资产/剧本来源'],
  ['Creation', '创建'],
  ['图谱 canvas', '图谱画布'],
  ['Feedback', '反馈'],
  ['queue', '队列'],
  ['运行中 tasks', '运行中的任务'],
  ['审计 Event', '审计事件'],
  ['事件 jsonl', '事件日志'],
  ['redacted', '已脱敏'],
  ['脱敏ed', '已脱敏'],
  ['交接包 / result', '交接包 / 结果'],
  ['broken reference', '断链引用'],
  ['br正常en reference', '断链引用'],
  ['结构 ok', '结构正常'],
  ['清单 ok', '清单正常'],
  ['摘要 ok', '摘要正常'],
  [' ok', ' 正常'],
  ['交接包 check', '交接包检查'],
  ['result 评审', '结果评审'],
  ['项目.json', '项目文件'],
  ['图谱.json', '图谱文件'],
  ['{studio_root}/项目s/film_a', '工作室根目录下的示例项目'],
  ['影响Report', '影响报告'],
  ['影响 report', '影响报告'],
  ['影响报告 failed', '影响报告失败'],
  ['refId', '引用标识'],
  ['GraphEdge', '图谱边'],
  ['Graph 不保存', '图谱不保存'],
  ['after 资产 change', '资产变更后'],
  ['有变更 after 资产 change', '资产变更后有变更'],
  ['已过期 after 资产 change', '资产变更后过期'],
  ['2 交接包 affected', '2 个交接包受影响'],
  ['layout 自动保存', '布局自动保存'],
  ['scene + 2 characters + 4 引用', '场景 + 2 个角色 + 4 个引用'],
  ['shot_提示词.v2', '镜头提示词 v2'],
  ['principles > context > skill > 结构', '原则 > 上下文 > 能力包 > 结构'],
  ['p评审 before submit', '提交前预览'],
  ['not 已创建 until confirm', '确认后才创建'],
  ['结构 validation', '结构校验'],
  ['生成交接包.status', '生成交接包状态'],
  ['镜头.status', '镜头状态'],
  ['交接包_就绪 after 清单 ok', '清单通过后交接包就绪'],
  ['清单 validation', '清单校验'],
  ['审计 event', '审计事件'],
  ['交接包.export.requested', '交接包导出请求'],
  ['pending_评审', '待评审'],
  ['approve / reject / 需要修订', '通过 / 拒绝 / 需要修订'],
  ['交接包 -> result -> 成片', '交接包 -> 结果 -> 成片'],
  ['评审.status.changed', '评审状态已变更'],
  ['Video结果', '视频结果'],
  ['Bound 镜头', '已绑定镜头'],
  ['Note', '笔记'],
  ['local 审计 必需', '需要本地审计'],
  ['适配器/配置 only', '仅适配器/配置'],
  ['scope check', '范围检查'],
  ['external transfer', '外部传输'],
  ['审计: writable', '审计：可写'],
  ['privacy: 本地优先', '隐私：本地优先'],
  ['提示词/runs', '提示词/运行记录'],
  ['blocking、warning、info', '阻断、警告、信息'],
  ['blocking', '阻断'],
  ['warning', '警告'],
  ['info', '信息'],
  ['asset index', '资产索引'],
  ['结构 version', '结构版本'],
  ['结构Version', '结构版本'],
  ['tmp', '临时文件'],
  ['rename', '重命名'],
  ['project-relative', '项目相对路径'],
  ['干净 shutdown', '干净关闭'],
  ['health check', '健康检查'],
  ['not 必需', '无需执行'],
  ['图谱节点.refId', '图谱节点引用标识'],
  ['refines', '版本链路'],
  ['图谱版本过期', '图谱版本过期'],
  ['new run', '新运行'],
  ['run records', '运行记录'],
  ['version 冲突', '版本冲突'],
  ['run record', '运行记录'],
  ['traversal 配置', '遍历配置'],
  ['placeholder', '占位'],
  ['physical delete unsafe', '物理删除不安全'],
  ['archive', '归档'],
  ['restore', '恢复'],
  ['relink', '重新链接'],
  ['unbundle', '解除打包'],
  ['uses / belongs_to / produces', '使用 / 归属 / 产出'],
  ['Relations', '关系'],
  ['bindings', '绑定'],
  ['staging', '暂存'],
  ['resultId', '结果标识'],
  ['submitted', '已提交'],
  ['data', '数据'],
  ['unsafe 交接包 path', '不安全交接包路径'],
  ['recoverable 草稿', '可恢复草稿'],
  ['4 资产 included', '包含 4 个资产'],
  ['export 清单', '导出清单'],
  ['skill、template 和 output contract', '能力包、模板和输出契约'],
  ['missing context', '缺少上下文'],
  ['编译 conflict', '编译冲突'],
  ['能力包Registry', '能力包注册表'],
  ['能力包Router', '能力包路由器'],
  ['run 记录', '运行记录'],
  ['run submit', '提交运行'],
  ['shot-提示词-optimizer@1.2', '镜头提示词优化器 1.2'],
  ['run record', '运行记录'],
  ['handoff 后', '交接后'],
  ['Adapters', '适配器'],
  ['UI 状态', '界面状态'],
  ['export', '导出'],
  ['b已锁定 by missing 资产', '因资产缺失被阻断'],
  ['docs/test', '测试文档目录'],
  ['run、security、结构', '运行、安全、结构'],
  ['security', '安全'],
  ['b已锁定 sample', '样例被阻断'],
  ['资产 excluded', '资产已排除'],
  ['health report', '健康报告'],
  ['审计 write', '审计写入'],
  ['issue', '任务'],
  ['Issue', '任务'],
  ['Goal、Scope、Out of Scope、Implementation Scope、验收 Criteria', '目标、范围、非范围、实现范围、验收标准'],
  ['脱敏 gate', '脱敏门禁'],
  ['portability proof 必需', '需要可移植性证明'],
  ['regression', '回归'],
  ['就绪 to run', '可运行'],
  ['manual script', '手动脚本'],
  ['09 Delivery', '09 交付'],
  ['Delivery', '交付'],
  ['选择 工作室根目录', '选择工作室根目录'],
  ['工作室根目录 Root', '工作室根目录'],
  ['face ref', '面部参考'],
  ['purpose', '用途'],
  ['2 已锁定 rules', '2 条锁定规则'],
  ['thumbnail index', '缩略图索引'],
  ['missing 资产', '缺失资产'],
  ['missing 来源', '缺失来源'],
  ['missing', '缺失'],
  ['relink 必需', '需要重新链接'],
  ['Continuity', '连续性'],
  ['schemaVersion', '结构版本'],
  ['version', '版本'],
  ['path', '路径'],
  ['event', '事件'],
  ['report', '报告'],
  ['validation', '校验'],
  ['check', '检查'],
  ['change', '变更'],
  ['affected', '受影响'],
  ['included', '已包含'],
  ['writable', '可写'],
  ['privacy', '隐私'],
  ['local', '本地'],
  ['only', '仅'],
  ['external', '外部'],
  ['scope', '范围'],
  ['required', '必需'],
]

const SOURCE_ROOT = '/Users/suqing/Coding/golang/00_self/tuyu-studio/docs/design/'
const PROTOTYPE_ROOT = '/Users/suqing/Coding/design/tuyu-design'

const slugWords: Record<string, string> = {
  '00': '00',
  '01': '01',
  '02': '02',
  '03': '03',
  '04': '04',
  '05': '05',
  '06': '06',
  '07': '07',
  '08': '08',
  '09': '09',
  product: '产品',
  scope: '边界',
  glossary: '术语',
  user: '用户',
  workflows: '工作流',
  local: '本地',
  project: '项目',
  storage: '存储',
  directory: '目录',
  layout: '布局',
  schema: '结构',
  migration: '迁移',
  save: '保存',
  lock: '锁',
  recovery: '恢复',
  health: '健康',
  check: '检查',
  creative: '创作',
  graph: '图谱',
  domain: '领域',
  model: '模型',
  nodes: '节点',
  edges: '边',
  state: '状态',
  machine: '机',
  context: '上下文',
  resolution: '解析',
  consistency: '一致性',
  rules: '规则',
  asset: '资产',
  library: '库',
  continuity: '连续性',
  ingestion: '导入',
  indexing: '索引',
  binding: '绑定',
  lineage: '血缘',
  deletion: '删除',
  script: '剧本',
  shot: '镜头',
  package: '交接包',
  workflow: '工作流',
  scene: '场次',
  card: '卡',
  lifecycle: '生命周期',
  export: '导出',
  result: '结果',
  review: '评审',
  instruction: '指令',
  stack: '栈',
  skills: '能力包',
  compile: '编译',
  order: '顺序',
  skill: '能力包',
  registry: '注册表',
  routing: '路由',
  output: '输出',
  contracts: '契约',
  conflict: '冲突',
  handling: '处理',
  ai: '人工智能',
  runtime: '运行时',
  provider: '供应商',
  adapters: '适配器',
  gateway: '网关',
  image: '图像',
  generation: '生成',
  adapter: '适配器',
  handoff: '交接',
  errors: '错误',
  retry: '重试',
  frontend: '前端',
  workbench: '工作台',
  experience: '体验',
  workspace: '工作区',
  canvas: '画布',
  interactions: '交互',
  inspector: '检查器',
  task: '任务',
  panels: '面板',
  production: '生产',
  feedback: '反馈',
  security: '安全',
  privacy: '隐私',
  observability: '可观测性',
  path: '路径',
  guard: '守卫',
  permissions: '权限',
  redaction: '脱敏',
  audit: '审计',
  events: '事件',
  delivery: '交付',
  acceptance: '验收',
  test: '测试',
  plan: '计划',
  slices: '切片',
  matrix: '矩阵',
  strategy: '策略',
  release: '发布',
  readiness: '就绪',
  readme: '说明',
  architecture: '架构',
  redacted: '脱敏',
  and: '与',
  to: '到',
  boundary: '边界',
}

const slugToZh = (value: string) =>
  value
    .replace(/\.md$/, '')
    .split('-')
    .map((part) => slugWords[part] ?? part)
    .join('')

export const zhSourcePath = (value?: string | null): string => {
  if (!value) return ''
  const trimmed = value.trim()
  if (trimmed === PROTOTYPE_ROOT) return '当前设计原型目录'
  if (trimmed === SOURCE_ROOT.slice(0, -1)) return '图屿源设计文档目录'

  const relative = trimmed.startsWith(SOURCE_ROOT) ? trimmed.slice(SOURCE_ROOT.length) : trimmed
  if (relative === 'README.md') return '源文档 / 设计总览'
  if (relative === 'details/README.md') return '源文档 / 设计详情索引'
  if (relative.startsWith('architecture/')) return `源文档 / ${slugToZh(relative)}`
  if (!relative.startsWith('details/')) return zhText(value)

  const [, moduleDir = 'details', file = 'README.md'] = relative.split('/')
  return `源文档 / ${slugToZh(moduleDir)} / ${file === 'README.md' ? '模块说明' : slugToZh(file)}`
}

const pathLike = (value: string) => {
  const trimmed = value.trim()
  return (
    trimmed.startsWith('/Users/') ||
    trimmed === 'README.md' ||
    /^(details|architecture)\/.+\.md$/.test(trimmed)
  )
}

const applyPairs = (value: string, pairs: Array<[string, string]>) =>
  pairs.reduce((current, [source, target]) => current.split(source).join(target), value)

export const zhText = (value?: string | null): string => {
  if (!value) return ''
  if (pathLike(value)) return value

  let text = applyPairs(value, phrasePairs)
  text = applyPairs(text, tokenPairs)

  for (const [source, target] of wordPairs) {
    text = text.replace(new RegExp(`\\b${source}\\b`, 'g'), target)
  }

  text = applyPairs(text, cleanupPairs)
  return applyPairs(text, cleanupPairs)
}
